version: '3.5'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdb